### ISSUE TITLE
[Task] onderzoek hoe visualisaties over MOZ in de labs website te plaatsen

### ISSUE THREAD

**Issue by jblom** [beeldengeluid/labs.beeldengeluid.nl#465]
Zie Pipeline voor MOZ viz document: https://docs.google.com/document/d/1eqEJZburgnnDcxjAy7Gi9iwO92pUixUMPvLFqZj-I6g/edit#heading=h.irece1fs776a

voor mogelijke oplossingen.

Wat context:
- Wel/niet tonen van visualisaties voor niet-open content
- IDs tussen LD en Elasticsearch komen niet altijd overeen
- nieuwe endpoint in search API dat enkel aggregaties teruggeeft kan problemen met ipr omzeilen

**Tasks**

- [x] Document aanvullen @phivk
- [x] Document aanvullen @jblom
- [x] Document aanvullen @wmelder
- [x] Bespreek voor- en nadelen van de opties in de groep
- [x] Kies de beste oplossing

**Comment by jblom** [comment]
issue over [nieuw endpoint](https://github.com/beeldengeluid/labs-search-api/issues/248) in search API (voor aggregaties)

**Comment by phivk** [comment]
Ik heb opties in het document aangevuld vanuit mijn perspectief

**Comment by mwigham** [comment]
Thank you!
